apiVersion: v1
kind: PersistentVolume
metadata:
  name: nextcloud-data-pv
spec:
  capacity:
    storage: 50Gi
  volumeMode: Filesystem
  accessModes:
    - ReadWriteMany
  persistentVolumeReclaimPolicy: Retain
  nfs:
    path: /srv/containers/nextcloud/data
    server: 10.8.24.20
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: nextcloud-html-pv
spec:
  capacity:
    storage: 10Gi
  volumeMode: Filesystem
  accessModes:
    - ReadWriteMany
  persistentVolumeReclaimPolicy: Retain
  nfs:
    path: /srv/containers/nextcloud/html
    server: 10.8.24.20
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: nextcloud-data-pvc
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 50Gi
  volumeName: nextcloud-data-pv
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: nextcloud-html-pvc
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 10Gi
  volumeName: nextcloud-html-pv
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: nextcloud
  labels:
    app: nextcloud
spec:
  replicas: 1
  selector:
    matchLabels:
      app: nextcloud
  template:
    metadata:
      labels:
        app: nextcloud
    spec:
      containers:
        - name: nextcloud-app
          image: docker.io/library/nextcloud:31
          ports:
            - containerPort: 80
          volumeMounts:
            - name: nextcloud-html
              mountPath: /var/www/html
            - name: nextcloud-data
              mountPath: /var/www/html/data
          resources:
            requests:
              memory: "512Mi"
              cpu: "500m"
            limits:
              memory: "4Gi"
              cpu: "2"
        - name: nextcloud-collabora
          image: docker.io/collabora/code:24.04.12.4.1
          env:
            - name: domain
              value: "cloud.lidsol.unam.mx"
            - name: "extra_params"
              value: "--o:ssl.enable=false --o:ssl.termination=true"
            - name: aliasgroup1
              value: "https://cloud.lidsol.unam.mx:443"
          ports:
            - containerPort: 9980
          resources:
            requests:
              memory: "512Mi"
              cpu: "500m"
            limits:
              memory: "2Gi"
              cpu: "1"
        - name: nextcloud-redis
          image: docker.io/library/redis:7
          ports:
            - containerPort: 6379
          resources:
            requests:
              memory: "128Mi"
              cpu: "250m"
            limits:
              memory: "256Mi"
              cpu: "500m"
      volumes:
        - name: nextcloud-html
          persistentVolumeClaim:
            claimName: nextcloud-html-pvc
        - name: nextcloud-data
          persistentVolumeClaim:
            claimName: nextcloud-data-pvc
---
apiVersion: v1
kind: Service
metadata:
  name: nextcloud
  labels:
    app: nextcloud
spec:
  selector:
    app: nextcloud
  ports:
    - name: http
      protocol: TCP
      port: 80
      targetPort: 80
    - name: collabora
      protocol: TCP
      port: 9980
      targetPort: 9980
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: nextcloud-ingress
  annotations:
    cert-manager.io/issuer: "https-issuer"
    nginx.ingress.kubernetes.io/proxy-body-size: "10G"
spec:
  ingressClassName: nginx
  tls:
  - hosts:
      - cloud.lidsol.unam.mx
    secretName: httpsnextcloud-tls
  rules:
  - host: cloud.lidsol.unam.mx
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: nextcloud
            port:
              number: 80
  - host: office.lidsol.unam.mx
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: collabora
            port:
              number: 9980